from .base_settings_tab import BaseSettingsTab
from .appearance_tab import AppearanceTab
from .general_tab import GeneralTab
from .playback_tab import PlaybackTab
from .library_tab import LibraryTab
from .cache_tab import CacheTab
from .about_tab import AboutTab
from .remote_tab import RemoteTab
from .services_tab import ServicesTab
